name: Semgrep Security Scan

on:
  push:
    branches:
      - main
      - prueba-semgrep

  pull_request:
    branches:
      - main

jobs:
  semgrep:
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: |
          semgrep scan --config=p/owasp-top-ten --error .
